### ISSUE TITLE
$ensure parameter to concat::fragment is deprecated

### ISSUE THREAD

**Issue by Phil-Friderici** [arioch/puppet-keepalived#112]
The usage of the parameter ensure in keepalived::vrrp::instance [1] is deprecated and should get removed.
It throws this warning message:
`Warning: Scope(Concat::Fragment[keepalived.conf_vrrp_instance_VI_1]): The $ensure parameter to concat::fragment is deprecated and has no effect.`

I will sent a PR to remove them.

[1] https://github.com/arioch/puppet-keepalived/blob/master/manifests/vrrp/instance.pp#L184

**Comment by arioch** [comment]
Closing after merging #114.
Thanks again. 👍

**Comment by Phil-Friderici** [comment]
My pleasure, thanks for reviewing and merging so fast :)
