### ISSUE TITLE
keepalived_version fact not working

### ISSUE THREAD

**Issue by aamerik** [arioch/puppet-keepalived#61]
Hi, I'm having issues with every agent run warning me on
```
Could not retrieve fact='keepalived_version', resolution='<anonymous>': undefined method `[]' for nil:NilClass
```

Can someone please help :)

**Comment by aamerik** [comment]
I see the fact does

```
Facter::Util::Resolution.exec('keepalived --version 2>&1').lines.first.match(/Keepalived v(\d\.\d\.\d) .+/)[1]
```

but my keepalived on RHEL outputs version as:

```
keepalived -v
Keepalived v1.2.13 (08/07,2014)
```

Is this the issue?

**Comment by arioch** [comment]
@petems could you take a look at this?

**Comment by petems** [comment]
@arioch Should be an easy enough fix I think:

```
Keepalived v(\d+\.\d+\.\d+)
```

Gimme a sec, I'll add a spec to catch this in the future too! :+1:

**Comment by arioch** [comment]
Thanks @petems!

**Comment by petems** [comment]
Fixed in https://github.com/arioch/puppet-keepalived/pull/63

**Comment by petems** [comment]
@arioch You can close this now :+1:

**Comment by arioch** [comment]
Alright, thanks again.
