### ISSUE TITLE
Comparison of: String < Integer, is not possible

### ISSUE THREAD

**Issue by lkthomas** [arioch/puppet-keepalived#79]
Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Comparison of: String < Integer, is not possible. Caused by 'A String is not comparable to a non String'. at /etc/puppetlabs/code/environments/production/modules/keepalived/manifests/vrrp/instance.pp:171:43 

# Setup Keepalived for HAProxy failover
	include ::keepalived

	keepalived::vrrp::instance { 'VI_50':
		interface         => 'eth0',
		state             => 'MASTER',
		virtual_router_id => '50',
		priority          => '101',
		auth_type         => 'PASS',
		auth_pass         => 'secret',
		virtual_ipaddress => [ '10.0.0.22/24' ],
		track_interface   => ['eth0'], # optional, monitor these interfaces.
		track_script	  => 'check_haproxy',
  	}

Anyone have idea why?

**Comment by lkthomas** [comment]
Found problem, please change example, refer value should be done without quotes:
                virtual_router_id =>  50,
                priority          =>  101,

**Comment by erikanderson** [comment]
I was having a similar issue, made PR https://github.com/arioch/puppet-keepalived/pull/80

**Comment by erikanderson** [comment]
@arioch @lkthomas I created a new PR which implements a better solution https://github.com/arioch/puppet-keepalived/pull/81

**Comment by erikanderson** [comment]
This can be closed, it was resolved by https://github.com/arioch/puppet-keepalived/pull/82
