### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by throwaway99** [arioch/puppet-keepalived#96]
Hi,

Sorry to be a pain - can I ask if you're planning to tag new release?

I'm using the new hiera support (thanks for that!) and would like to track a released version of the moduke from the forge rather than pull a particular git hash from Github or maintain a profile::keepalived class to provide the same functionality.

Thanks.

**Comment by arioch** [comment]
Not to worry!
Here you go: [1.2.4](https://forge.puppetlabs.com/arioch/keepalived/1.2.4/readme). :+1:
